# Generated by Django 5.2.8 on 2025-11-21 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculine', 'Masculine'), ('Feminine', 'Feminine'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='DrawingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'drawing page',
                'verbose_name_plural': 'drawing pages',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drawings/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('drawing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.drawingpage')),
            ],
            options={
                'verbose_name': 'drawing',
                'verbose_name_plural': 'drawings',
            },
        ),
    ]
